/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jerod
 */
public class HelpContentsGUI extends javax.swing.JFrame {

    /**
     * Creates new form HelpContentsGUI
     */
    public HelpContentsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HowToUse = new javax.swing.JButton();
        WhatToCome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HelpTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HowToUse.setText("How To Use");
        HowToUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowToUseActionPerformed(evt);
            }
        });
        getContentPane().add(HowToUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        WhatToCome.setText("What's To Come");
        WhatToCome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhatToComeActionPerformed(evt);
            }
        });
        getContentPane().add(WhatToCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        HelpTextArea.setColumns(20);
        HelpTextArea.setLineWrap(true);
        HelpTextArea.setRows(5);
        HelpTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(HelpTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 240, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HowToUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowToUseActionPerformed
        HelpTextArea.removeAll();
        HelpTextArea.setText("Just use it when it feels right. You will know!");
    }//GEN-LAST:event_HowToUseActionPerformed

    private void WhatToComeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhatToComeActionPerformed
        HelpTextArea.removeAll();
        HelpTextArea.setText("Hopefully some more sounds and transition to portables");
    }//GEN-LAST:event_WhatToComeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpContentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpContentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpContentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpContentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpContentsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea HelpTextArea;
    private javax.swing.JButton HowToUse;
    private javax.swing.JButton WhatToCome;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
