/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

;
import java.applet.Applet;
   import java.applet.AudioClip;
   import java.net.URL;
   import java.awt.Toolkit;
import javax.swing.ImageIcon;

public class StartGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("iconAS.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SadTrombone = new javax.swing.JButton();
        Crickets = new javax.swing.JButton();
        Applause = new javax.swing.JButton();
        Dramatic1 = new javax.swing.JButton();
        Sensored = new javax.swing.JButton();
        Awe = new javax.swing.JButton();
        Scream = new javax.swing.JButton();
        JokeDrum1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        HelpContents = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        About = new javax.swing.JMenuItem();
        Info = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Awkward Sound Bar");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("For Those Awkward Moments In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 90));

        SadTrombone.setText("Sad Trombone");
        SadTrombone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SadTromboneActionPerformed(evt);
            }
        });
        getContentPane().add(SadTrombone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, 70));

        Crickets.setText("Crickets");
        Crickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CricketsActionPerformed(evt);
            }
        });
        getContentPane().add(Crickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, 70));

        Applause.setText("Applause");
        Applause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplauseActionPerformed(evt);
            }
        });
        getContentPane().add(Applause, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 70));

        Dramatic1.setText("Dramatic");
        Dramatic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dramatic1ActionPerformed(evt);
            }
        });
        getContentPane().add(Dramatic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 70));

        Sensored.setText("Sensored");
        Sensored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SensoredActionPerformed(evt);
            }
        });
        getContentPane().add(Sensored, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 140, 70));

        Awe.setText("Awwwee!");
        Awe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AweActionPerformed(evt);
            }
        });
        getContentPane().add(Awe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 140, 70));

        Scream.setText("Scream");
        Scream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreamActionPerformed(evt);
            }
        });
        getContentPane().add(Scream, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 140, 70));

        JokeDrum1.setText("Joke Drum");
        JokeDrum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JokeDrum1ActionPerformed(evt);
            }
        });
        getContentPane().add(JokeDrum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 140, 70));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Life");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 660, -1));

        jLabel4.setText("       ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        HelpContents.setText("Help Contents");
        HelpContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpContentsActionPerformed(evt);
            }
        });
        jMenu2.add(HelpContents);
        jMenu2.add(jSeparator1);

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        Info.setText("Info");
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });
        jMenu2.add(Info);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SadTromboneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SadTromboneActionPerformed
URL url = getClass().getResource("sad");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();        clip.play();    }//GEN-LAST:event_SadTromboneActionPerformed

    private void CricketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CricketsActionPerformed
        URL url = getClass().getResource("cricket 2");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();
    }//GEN-LAST:event_CricketsActionPerformed

    private void ApplauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplauseActionPerformed
        URL url = getClass().getResource("applause3.wav");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();
        
    }//GEN-LAST:event_ApplauseActionPerformed

    private void Dramatic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dramatic1ActionPerformed
        URL url = getClass().getResource("dundundun");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();
    }//GEN-LAST:event_Dramatic1ActionPerformed

    private void SensoredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SensoredActionPerformed
        URL url = getClass().getResource("censor");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();
    }//GEN-LAST:event_SensoredActionPerformed

    private void AweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AweActionPerformed
        URL url = getClass().getResource("awe");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();
    }//GEN-LAST:event_AweActionPerformed

    private void ScreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreamActionPerformed
        URL url = getClass().getResource("scream");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();
    }//GEN-LAST:event_ScreamActionPerformed

    private void JokeDrum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JokeDrum1ActionPerformed
        URL url = getClass().getResource("JokeDrum");    
        AudioClip clip = Applet.newAudioClip(url);
        clip.play();
    }//GEN-LAST:event_JokeDrum1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void HelpContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpContentsActionPerformed
       new HelpContentsGUI().setVisible(true);
    }//GEN-LAST:event_HelpContentsActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
       new AboutGUI().setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        new InfoGUI().setVisible(true);
    }//GEN-LAST:event_InfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton Applause;
    private javax.swing.JButton Awe;
    private javax.swing.JButton Crickets;
    private javax.swing.JButton Dramatic1;
    private javax.swing.JMenuItem HelpContents;
    private javax.swing.JMenuItem Info;
    private javax.swing.JButton JokeDrum1;
    private javax.swing.JButton SadTrombone;
    private javax.swing.JButton Scream;
    private javax.swing.JButton Sensored;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
